# Generated by Django 3.0 on 2019-12-12 18:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djfirst', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_desc', models.TextField()),
                ('item_display', models.DateTimeField(default=datetime.datetime(2019, 12, 27, 18, 4, 54, 359746))),
                ('item_weight', models.FloatField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_item', to='djfirst.Cart')),
            ],
        ),
    ]
